---
# Realiza o download de anexo em um e-mail no Exchange Web 2016
name: Download Anexo Email

on:
  schedule:
    # 2022-01-01 00:00:00
    - cron: "0 0 1 1 *"

jobs:
  download-email:
    steps:
      - name: Login
        uses: plugins/exchange2016
        with:
          url: https://cas.exemplo.com.br/owa/
          username: dominio\usuario
          password: minhasenha
